### ISSUE TITLE
TOKEN INVALID

### ISSUE THREAD

**Issue by doctordubba** [Zusier/Discord-Gift-Bot#2]
Hi this program is having identical issues to the Nitro sniper that you resolved. I downgraded discordjs to 12.2.0 but I'm guessing there was more at play.

**Comment by Zusier** [comment]
ah, forgot that this will probably have the same issue, give me one minute :)

**Comment by Zusier** [comment]
ok, fixed. the actual version is 11.6.4 but dependabot is weird

**Comment by doctordubba** [comment]
Thanks :)
